apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: __APP_NAME__-dc
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: __APP_NAME__
    spec:
      containers:
      - name: __APP_NAME__-ctr
        image: >-
          __IMAGE__
        ports:
        - name: pyfln-auth-port
          containerPort: 8000
        env:
          - name: UI_ENDPOINT
            value: "http://pyfln-ui:8080/"


